package com.test.amaro.amarotest.api;

import com.test.amaro.amarotest.entity.Feed;

import retrofit2.Call;
import retrofit2.http.GET;

public interface AmaroApi {

    //generally the path for REST APIS are readable
    //this number was the api generated by the mocked backend
    @GET("59b6a65a0f0000e90471257d")
    Call<Feed> getFeed();

    //other methods for this API goes here

}
